---
title: "Toy model description"
output: html_notebook
---

There are `r nfleets` fleets with `r ships_per_fleet[1]` "ships" each. The fleets carry permits for crabs, salmon, or both crabs and salmon. The legal crab season lasts the first `r which(pop_seasons['crab',] != 0 & pop_seasons['crab',] != 1)` weeks of the year (Dec. 1 - Aug. 14). The legal salmon season lasts from week `r which(pop_seasons['salmon',] != 0 & pop_seasons['salmon',] != 1)[1]` to `r which(pop_seasons['salmon',] != 0 & pop_seasons['salmon',] != 1)[2]` (May 1 - Oct. 31). Price per unit weight of crab and salmon, average recruitment of crab and salmon, and average weight per individual are all scaled to 1. Note that prices are assumed to be fixed. In the future, the stocks do not have to be equal with respect to these variables, and we will likely only acheive realistic dynamics by changing this. CVs of growth and recruitment are both set to 20% for both stocks. Recruitment and weight at recruitment are simulated from a lognormal distribution that can, in the future, include covariance among stocks and/or years. Weekly variable costs for each ship in the fleet follow a lognormal distribution with a 15% CV. Variable costs are correlated by ship. That is, if a ship can cheaply fish for crab, it can also cheaply fish for salmon. Right now the correlation on the log scale is `r cost_corr`, but that is arbitrary. The salmon TAC is `r salmon_tac_rule` of the pre-season population size. Could instead define TAC as N - escapement goal? There is no TAC for crabs.

<!-- Fixed costs for the year (assumed to be constant in time) are calculated as 30% of average crab revenue and 10% of average salmon revenue. For crab, average revenue is calculated as the product of average weight, average recruitment, and price, divided by the number of ships targeting that stock (i.e., single permit fleet size plus dual permit fleet size). This assumes all recruits to the fishery are caught in an average year. Note this never *actually* happens, because only a fraction of the remaining stock is caught each week. For salmon, that quantity is further multiplied by the proportion of recruitment at which the total allowable catch (TAC) is set, assumed to be `r salmon_tac_rule`. This assumes that the entire TAC is caught in an average year (which can actually happen). -->

Cost per trip is scaled so that in the average year, costs = revenue. However, given a fixed cost, calculating the variable cost such that, on average, annual costs cover annual revenue cannot be done explicitly. I used univariate root-solving to find the cost per trip that allows revenue to cover costs (fixed + variable) in an average year. Revenue in week $w$, $Rev_w$ is defined as:
$$Rev_w = N_w \cdot W \cdot P \cdot  q $$
where $N_w$ is the number of fish/crabs left in the population in week $w$, $W$ is the weight at recruitment, $P$ is the price per unit weight, and $q$ is catchability (unitless, less than 1). 
For simplicity (for now?), this was done independently for the two fisheries, and did not account for the fact that dual permit ships could switch to the other fishery. I iteratively selected a fixed cost and then solved for the variable cost until I achieved a satisfactory ratio of fixed to variable costs and a satisfactory percent of the population harvested in a year. For crab, the ratio of fixed to variable costs is 0.59 and 85% of the population is harvested. (Not good?!?) For salmon, the ratio is 0.11 and 19% of the population is harvested.

To avoid monte carlo error during root finding, instead of *simulating* a variable cost for each ship, I divided the unit interval into evenly spaced sub-intervals equal to the number of ships, and calculated the inverse CDF of the lognormal distribution at each quantile. The value of the inverse CDF at a given quantile was assumed to be that ship's weekly cost of fishing.

Fishers were not assumed to interfere with one another and catch rates within a week are independent of the numbers of vessels fishing. I am currently modeling in-season depletion for both populations. The accounting is much easier if I am consistent between the two populations, and only 20% of the salmon population is caught in a season anyway so it shouldn't make a huge difference either way. There is no natural mortality. Catchability, which I define as the proportion of the available stock that is caught by one "ship" in one week, is modeled as constant. (This means catch rates go down through the season.) Right now, catchability for crab assumes `r catchability['crab'] * sum(ships_per_fleet[c('crab', 'both')]) * 100`% of crab recruits are caught in the first week. Catchability is `r catchability[1]/catchability[2]` times lower for salmon (i.e., `r catchability[1]/catchability[2]` times fewer individuals caught per ship per week given the same population size). Note that you should only adjust catchability or average recruitment and fix the other parameter because they have the same effect.


```{r, include=FALSE}
# I need:
# CV wt_at_rec
# CV recruitment
# Figure out units. What parameters actually drive dynamics/which can be fixed to 1?
# E.g., if response variables of interested are all related to catch, then catchability and biomass influence results jointly, never separately
# (But, separately could be useful when thinking about ecological scenarios down the road)
# Better understand dynamics of fishing through season, esp. for salmon, for tuning

# Farther down the road:
# Add groundfish (sablefish-ish?)
# Correlation structure to stochastic components
# Once you switch gears you don't go back

# fixed cost is per season (capital of boat, annual maintenance, permits
# important because will allow people to operate at a loss

# extra normal profit (rent): more profit than a normal return on investment, like
# the stock market, when it's positive people entry fishery, use their licenses
# in a normal year, profits should cover costs just barely

# what is the avg revenue? e.g., set the price to 1. You know what the avg. total
# revenue is. Then choose a fleet size. Either have more than 3 in fleet or allow
# for fractions. Dan says easier to make fleet discrete. 
# On an avg year given total catch, divided evenly among vessels, fixed costs are
# 1/4 or total revenue and 3/4 of revenue is variable costs. No more than 1/3.
# For salmon maybe 1/10. 

# Prop. fixed to variable costs could be a model parameter that varies by fishery.
# Start with equal sized fleets. 

# permit price should increase to soak up extra profit. we won't model unidirectional
# change, something that is variable but not directionally so. so then we won't 
# let permit price vary. 

# at the start of the season you have fleet, they get signal of recruitment,
# some of the less profitable ones realize they won't make it, don't enter.
# for now say they know recruitment perfectly, and assume the same   number of vessels that 
# fished last year.
# Something that I should pay attention to: one fishery is more capital intensive

```